name: Update application version after release has been published

on:
  release:
    types: [published]

jobs:
  bump_release:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Update version
      id: update-version
      run: GITHUB_REF=$GITHUB_REF sh scripts/update-version.sh
    - name: Test output
      run: cat package.json
